name: Bicep Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      RunOnEnvironment:
        description: "Deploy to"
        required: true
        default: "Development"
        type: choice
        options:
          - Development
          - Pre-Production
          - Production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Azure Login (OIDC)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #  Optional - Validate before deploy
      - name: Validate Bicep
        run: |
          az deployment sub validate \
            --location australiaeast \
            --template-file ADE/main.bicep \
            --parameters @ADE/parameters.json \
            --parameters catalogRepoPat=${{ secrets.CATALOG_PAT }}

      #  Deploy Bicep
      - name: Deploy Bicep
        run: |
          az deployment sub create \
            --name main-${{ github.run_id }} \
            --location australiaeast \
            --template-file ADE/main.bicep \
            --parameters @ADE/parameters.json \
            --parameters catalogRepoPat=${{ secrets.CATALOG_PAT }}
